config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'music_players#index'

  resources :music_players, only: [:index, :create]
  namespace :music do
    resources :all_shuffle_plays, only: [:index, :show]
      get('all_mp3-shuffle', to: 'all_shuffle_plays#index')
      get('all_flac-shuffle', to: 'all_shuffle_plays#index')
    resources :latest2weeks, only: [:index, :show]
      get('2weeks_mp3-shuffle', to: 'latest2weeks#index')
      get('2weeks_flac-shuffle', to: 'latest2weeks#index')
    resources :playlist_themes, only: [:index, :show]
      get('mp3-next', to: 'playlist_themes#index')
      get('flac-next', to: 'playlist_themes#index')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/djmix_list.rb
class DjmixList < ApplicationRecord
  self.table_name = 'music_lists'

  belongs_to :djmix, class_name: 'Piston2438Mix', foreign_key: 'djmix_id'

  # アーティストを回数の多い順に並び替える。
    # SELECT artist, COUNT(*) AS ArtistCount FROM music_lists GROUP BY artist HAVING (ArtistCount > 2) ORDER BY ArtistCount DESC;
end

app/models/piston2438_mix.rb
class Piston2438Mix < ApplicationRecord
  self.table_name = 'piston2438_djmixes'

  has_many :music_lists, class_name: 'DjmixList', foreign_key: 'djmix_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/music/all_shuffle_plays_controller.rb
class Music::AllShufflePlaysController < ApplicationController
  before_action :authenticate_user!

  def index
    if request.fullpath.include? 'all_mp3-shuffle'
      @music = MixmachineDjmix.readonly.sample
      while session[:already_play].include?(@music.id) do
        @music = MixmachineDjmix.readonly.sample
      end

      session[:already_play].unshift @music.id
      session[:already_play].delete_at(25)
      redirect_to(action: 'show', id: @music.id, category: 'MP3')
    elsif request.fullpath.include? 'all_flac-shuffle'
      @music = MixmachineDjmix.readonly.sample
      while session[:already_play].include?(@music.id) do
        @music = MixmachineDjmix.readonly.sample
      end

      session[:already_play].unshift @music.id
      session[:already_play].delete_at(25)
      redirect_to(action: 'show', id: @music.id, category: 'FLAC')
    end
  end

  def show
    @music = MixmachineDjmix.readonly.find(params[:id])
  end
end

app/controllers/music/latest2weeks_controller.rb
class Music::Latest2weeksController < ApplicationController
  before_action :authenticate_user!

  def index
    if session[:playlists].length == 0
      redirect_to root_path
    else
      if request.fullpath.include? '2weeks_mp3-shuffle'
        redirect_to(action: 'show', id: session[:playlists][0]['id'], category: 'MP3')
      elsif request.fullpath.include? '2weeks_flac-shuffle'
        redirect_to(action: 'show', id: session[:playlists][0]['id'], category: 'FLAC')
      end
    end
  end

  def show
    @music = MixmachineDjmix.readonly.find(params[:id])
    session[:playlists].shift
  end
end

app/controllers/music/playlist_themes_controller.rb
class Music::PlaylistThemesController < ApplicationController
  before_action :authenticate_user!

  def index
    if session[:playlists].length == 0
      redirect_to root_path
    else
      if request.fullpath.include? 'mp3-next'
        redirect_to(action: 'show', id: session[:playlists].shift, category: 'MP3')
      elsif request.fullpath.include? 'flac-next'
        redirect_to(action: 'show', id: session[:playlists].shift, category: 'FLAC')
      end
    end
  end

  def show
    @music = Piston2438Mix.readonly.find(params[:id])

    if params[:category] == 'MP3'
      @category = 'MP3（320kbps）'
    elsif params[:category] == 'FLAC'
      @category = 'ロスレスオーディオ'
    end

    unless session[:playlists].blank?
      session[:playlists].shuffle!
      @next_music = Piston2438Mix.select(:id, :title, :release_date).readonly.find(session[:playlists][0])
    end
  end
end

app/controllers/music_players_controller.rb
class MusicPlayersController < ApplicationController
  before_action :authenticate_user!

  def index
    session[:playlists] = nil
  end

  def create
    session[:playlists] = Array.new

    if music_params[:play_method] == '全曲シャッフル再生'
      Piston2438Mix.select(:id).readonly.each do |djmix|
        session[:playlists] << djmix[:id]
      end

    elsif music_params[:play_method] == 'anime'
      DjmixList.find_by_sql("
        SELECT DISTINCT djmix_id FROM music_lists
          WHERE name LIKE 'アンパンマン%'
          OR name LIKE '%ドラえもん'
          OR name LIKE '%ポケモンマスター'
          OR name LIKE 'ようかい体操第一%'
          OR name='残酷な天使のテーゼ'
          OR name='にゃん酷なにゃんこのテーゼ'
          OR name='紅蓮華'
          OR name LIKE 'さんぽ%'
          OR name='PPAP'
          OR name='PIKACHU'
          OR name='パプリカ'
          OR name LIKE '%ドラゴンクエスト%'
          OR name LIKE '呼び込み君%'
      ").each do |djmix|
        session[:playlists] << djmix[:djmix_id]
      end

    elsif music_params[:play_method] == 'idol'
      DjmixList.find_by_sql("
        SELECT DISTINCT djmix_id FROM music_lists
          WHERE artist='SMAP'
          OR artist='嵐'
          OR artist='AKB48'
          OR artist='TWICE'
          OR artist='NIZIU'
      ").each do |djmix|
        session[:playlists] << djmix[:djmix_id]
      end

    elsif music_params[:play_method] == '2021-06'
      Piston2438Mix.find_by_sql("
        SELECT id FROM piston2438_djmixes WHERE release_date >= '2021-06-01'
      ").each do |djmix|
        session[:playlists] << djmix[:id]
      end
    end

    session[:playlists].uniq!
    session[:playlists].shuffle!
    redirect_to music_playlist_theme_path(id: session[:playlists].shift, category: music_params[:category])
  end

  private
  def music_params
    params.permit(:play_method, :category)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(page_title = '')
    base_title = 'Hirano_Tech Streaming Player'

    page_title.empty? ? base_title : page_title + " | " + base_title
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield :title ) %></title>
    <meta name='viewport' content='width=device-width,initial-scale=1' />
    <meta name='robots' content='noindex' />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <section id='Contents'>
      <%= yield %>
    </section>

    <footer>
      <%= link_to root_path, class: 'Footer-Menu btn btn-outline-dark' do %>
        <div>
          <i class='fas fa-home'></i><br />
          <span class='Footer-Menu--Text'>ホーム</span>
        </div>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to destroy_user_session_path, method: :delete, class: 'Footer-Menu btn btn-outline-dark' do %>
          <div>
            <i class='fas fa-sign-out-alt'></i><br />
            <span class='Footer-Menu--Text'>ログアウト</span>
          </div>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: 'Footer-Menu btn btn-outline-dark' do %>
          <div>
            <i class='fas fa-sign-in-alt'></i><br />
            <span class='Footer-Menu--Text'>ログイン</span>
          </div>
        <% end %>
      <% end %>
    </footer>
  </body>
</html>

app/views/music/all_shuffle_plays/show.html.erb
<section id='Contents' class='container'>
  <div class='Music-Prayer'>
    <h1 class='Music-Prayer__Title'>
      <span>MIX MACHINE</span>
    </h1>
    <h2 class='Mix-Machine__Tag'><%= link_to 'J-WAVE', 'https://www.j-wave.co.jp', target: '_blank' %></h2>

    <p class='Music-Prayer__Profile'>
      ● <%= @music.title %><br />
      <span class='Music-Prayer__Profile--Date'><%= @music.release_date.strftime('%Y年%m月%d日 %A') %></span><br />
      <%= image_tag 'https://due0xnee3ffkt.cloudfront.net/Images/GROOVE-LINE.webp', width: '75%', class: 'Music-Prayer__Profile--Image' %>
    </p>

    <% if params[:category] == 'MP3' %>
      <%= audio_tag("https://due0xnee3ffkt.cloudfront.net/MIX MACHINE（MP3）/#{@music.name}.mp3", controls: true, autoplay: true, class: 'Music-Prayer--Audio', onended: "location.href='/music/all_mp3-shuffle'; ") %>
    <% elsif params[:category] == 'FLAC' %>
      <%= audio_tag("https://due0xnee3ffkt.cloudfront.net/MIX MACHINE（FLAC）/#{@music.name}.flac", controls: true, autoplay: true, class: 'Music-Prayer--Audio', onended: "location.href='/music/all_flac-shuffle'; ") %>
    <% end %>
  </div>
</section>

app/views/music/latest2weeks/show.html.erb
<section id='Contents' class='container'>
  <div class='Music-Prayer'>
    <h1 class='Music-Prayer__Title'>
      <span>MIX MACHINE</span>
    </h1>
    <h2 class='Mix-Machine__Tag'><%= link_to 'J-WAVE', 'https://www.j-wave.co.jp', target: '_blank' %></h2>

    <p class='Music-Prayer__Profile'>
      ● <%= @music.title %><br />
      <span class='Music-Prayer__Profile--Date'><%= @music.release_date.strftime('%Y年%m月%d日 %A') %></span><br />
      <%= image_tag 'https://due0xnee3ffkt.cloudfront.net/Images/GROOVE-LINE.webp', width: '75%', class: 'Music-Prayer__Profile--Image' %>
    </p>

    <% if params[:category] == 'MP3' %>
      <%= audio_tag("https://due0xnee3ffkt.cloudfront.net/MIX MACHINE（MP3）/#{@music.name}.mp3", controls: true, autoplay: true, class: 'Music-Prayer--Audio', onended: "location.href='/music/2weeks_mp3-shuffle'; ") %>
    <% elsif params[:category] == 'FLAC' %>
      <%= audio_tag("https://due0xnee3ffkt.cloudfront.net/MIX MACHINE（FLAC）/#{@music.name}.flac", controls: true, autoplay: true, class: 'Music-Prayer--Audio', onended: "location.href='/music/2weeks_flac-shuffle'; ") %>
    <% end %>
  </div>
</section>

app/views/music/playlist_themes/show.html.erb
<% content_for(:title, @music.title) %>

<section id='Player-Page'>
  <div class='Piston2438_DJ-Player card'>
    <%= image_tag 'https://due0xnee3ffkt.cloudfront.net/Images/GROOVE-LINE.webp', alt: '【J-WAVE】GROOVE LINE', class: 'card-img-top' %>
    <p class='Category badge rounded-pill bg-secondary'><%= @category %></p>

    <div class='card-body'>
      <h2 class='Piston2438_DJ-Player--Title card-title'><%= @music.title %></h2>
      <p class='Piston2438_DJ-Player--Date card-text'><%= @music.release_date.strftime('%Y年%m月%d日 %A') %></p>

      <% if params[:category] == 'MP3' %>
        <%= audio_tag("https://due0xnee3ffkt.cloudfront.net/MIX MACHINE（MP3）/#{@music.name}.mp3", controls: true, autoplay: true, class: 'Piston2438_DJ-Player--Audio', onended: "location.href='/music/mp3-next';") %>
      <% elsif params[:category] == 'FLAC' %>
        <%= audio_tag("https://due0xnee3ffkt.cloudfront.net/MIX MACHINE（FLAC）/#{@music.name}.flac", controls: true, autoplay: true, class: 'Piston2438_DJ-Player--Audio', onended: "location.href='/music/flac-next';") %>
      <% end %>

      <% unless session[:playlists].blank? %>
        <h3 class='Piston2438_DJ-Player--Next-Length card-title'>
          終了まで、残り<span><%= session[:playlists].length %></span>曲です。
        </h3>
        <p class='Piston2438_DJ-Player--Next-Title'>
          <span class='badge rounded-pill bg-secondary'>次曲</span><%= @next_music[:title] %>
        </p>
      <% end %>
    </div>
  </div>
</section>

app/views/music_players/index.html.erb
<% content_for(:title, 'ホーム') %>

<section id='Top-Page'>
  <div class='Piston2438_DJMIX card'>
    <%= image_tag 'https://due0xnee3ffkt.cloudfront.net/Images/GROOVE-LINE.webp', alt: '【J-WAVE】GROOVE LINE', class: 'card-img-top' %>
    <div class='card-body'>
      <h2 class='Piston2438_DJMIX--Title card-title'>ピストン西沢 Non-STOP DJ MIX♪</h2>

      <%= form_with url: music_players_path, method: 'POST', class: 'Piston2438_DJMIX__Form', local: true do |form| %>
        <h3 class='Piston2438_DJMIX__Form--Title card-title'>● 再生形式を選択してください。</h3>
        <div class='Piston2438_DJMIX__Form__Select'>
          <%= form.radio_button :category, 'MP3', checked: true, class: 'form-check-input', id: 'Mobile_MP3' %>
          <%= form.label :category, 'モバイルデータ通信（MP3）', class: 'Piston2438_DJMIX__Form__Select--Text form-check-label', for: 'Mobile_MP3' %><br />
          <%= form.radio_button :category, 'FLAC', class: 'form-check-input', id: 'High-Quality_FLAC' %>
          <%= form.label :category, 'ロスレスオーディオ（FLAC）', class: 'Piston2438_DJMIX__Form__Select--Text form-check-label', for: 'High-Quality_FLAC' %><br />
        </div>

        <h3 class='Piston2438_DJMIX__Form--Title card-title'>● 再生方法を選択してください。</h3>
        <div class='Piston2438_DJMIX__Form__Select'>
          <%= form.radio_button :play_method, '全曲シャッフル再生', checked: true, class: 'form-check-input', id: 'All-Shuffle_Songs' %>
          <%= form.label :play_method, '全曲シャッフル再生', class: 'Piston2438_DJMIX__Form__Select--Text form-check-label', for: 'All-Shuffle_Songs' %><br />

          <%= form.radio_button :play_method, 'anime', class: 'form-check-input', id: 'Anime_Songs' %>
          <%= form.label :play_method, 'ピストン西沢渾身のキッズソング 特集！', class: 'Piston2438_DJMIX__Form__Select--Text form-check-label', for: 'Anime_Songs' %><br />

          <%= form.radio_button :play_method, 'idol', class: 'form-check-input', id: 'Idol_Songs' %>
          <%= form.label :play_method, '日韓アイドル ごちゃ混ぜミックス !!!', class: 'Piston2438_DJMIX__Form__Select--Text form-check-label', for: 'Idol_Songs' %><br />

          <%= form.radio_button :play_method, '2021-06', class: 'form-check-input', id: '2021-06' %>
          <%= form.label :play_method, '2021年6月 放送回', class: 'Piston2438_DJMIX__Form__Select--Text form-check-label', for: '2021-06' %><br />
        </div>

        <%= form.submit "Let's Drop IT♪", class: 'Piston2438_DJMIX__Form--Submit btn btn-outline-primary' %>
      <% end %>
    </div>
  </div>
</section>